name: Autograding Tests
on: [push, workflow_dispatch]
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - run: npm install
    - name: Test1
      id: test1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test1
        command: npm test -- test1
        timeout: 10
        max-score: 1
    - name: Test2
      id: test2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test2
        command: npm test -- test2
        timeout: 10
        max-score: 1
    - name: Test3
      id: test3
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test3
        command: npm test -- test3
        timeout: 10
        max-score: 1
    - name: Test4
      id: test4
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test4
        command: npm test -- test4
        timeout: 10
        max-score: 1
    - name: Test5
      id: test5
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test5
        command: npm test -- test5
        timeout: 10
        max-score: 1
    - name: Test6
      id: test6
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test6
        command: npm test -- test6
        timeout: 10
        max-score: 1
    - name: Test7
      id: test7
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test7
        command: npm test -- test7
        timeout: 10
        max-score: 1
    - name: Test8
      id: test8
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test8
        command: npm test -- test8
        timeout: 10
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST1_RESULTS: "${{steps.test1.outputs.result}}"
        TEST2_RESULTS: "${{steps.test2.outputs.result}}"
        TEST3_RESULTS: "${{steps.test3.outputs.result}}"
        TEST4_RESULTS: "${{steps.test4.outputs.result}}"
        TEST5_RESULTS: "${{steps.test5.outputs.result}}"
        TEST6_RESULTS: "${{steps.test6.outputs.result}}"
        TEST7_RESULTS: "${{steps.test7.outputs.result}}"
        TEST8_RESULTS: "${{steps.test8.outputs.result}}"
      with:
        runners: test1,test2,test3,test4,test5,test6,test7,test8
